"""Pinned sha256 values for every dist artifact (generated file).

Generated by tools/dist/gen-dist-pins.sh from the determinism-checked tarballs;
do not edit by hand. All-zero placeholders mean the product tarball has not
been built + published yet for that architecture: dist.bzl fails fast with a
clear message if such a repo is ever fetched (e.g. by //image:image).
"""

PIN_OPENSSH_AMD64 = "0000000000000000000000000000000000000000000000000000000000000000"
PIN_OPENSSH_ARM64 = "98cb29ab8de1d8fdc4bd7061599eee3888e6cf5ed549b2599f0f1a4c4adf0410"

PIN_GIT_AMD64 = "0000000000000000000000000000000000000000000000000000000000000000"
PIN_GIT_ARM64 = "8e9c48dcdfee9ecdcb273a737d5d2bbd93401586f93e99f496dd60ca724cf422"

PIN_FISH_AMD64 = "0000000000000000000000000000000000000000000000000000000000000000"
PIN_FISH_ARM64 = "b7d4a38c7114b49f07c32d5c808ef3294730f8e2ee4e555de7f9b6d51c7e35f5"

# Real pin: verified locally with two byte-identical builds of the pinned
# Alpine ca-certificates apk (tools/dist/build-ca-certs.sh).
PIN_CA_CERTS_AMD64 = "0000000000000000000000000000000000000000000000000000000000000000"
PIN_CA_CERTS_ARM64 = "519184eaa016f8ecdee166823b418696e6073a8b2a44ae86f795b70d7a77faf6"

PIN_CONTAINERD_AMD64 = "0000000000000000000000000000000000000000000000000000000000000000"
PIN_CONTAINERD_ARM64 = "2d35e5ac69ac40dd981a84fa1c9742cbf7f71575e534f5b79e0bc10b9a61a313"

PIN_RUNC_AMD64 = "0000000000000000000000000000000000000000000000000000000000000000"
PIN_RUNC_ARM64 = "83925040becee494c31f523207aaf6eea4fbeb4561011bbaa4866a35b0d00306"

DIST_PINS = {
    "openssh": {"amd64": PIN_OPENSSH_AMD64, "arm64": PIN_OPENSSH_ARM64},
    "git": {"amd64": PIN_GIT_AMD64, "arm64": PIN_GIT_ARM64},
    "fish": {"amd64": PIN_FISH_AMD64, "arm64": PIN_FISH_ARM64},
    "ca-certs": {"amd64": PIN_CA_CERTS_AMD64, "arm64": PIN_CA_CERTS_ARM64},
    "containerd": {"amd64": PIN_CONTAINERD_AMD64, "arm64": PIN_CONTAINERD_ARM64},
    "runc": {"amd64": PIN_RUNC_AMD64, "arm64": PIN_RUNC_ARM64},
}