"""Repository rules for pinned distribution artifacts.

Phase 2 (tools/dist) replaces the Phase-1 placeholder with real artifacts.
Each product (openssh, git, fish, sudo, ca-certificates, containerd, runc) is
fetched from the GitHub Releases mirror (primary, R3-Q2) with an S3 fallback
URL; both URLs must match the per-architecture sha256 pin from
//:dist_pins.bzl (generated by tools/dist/gen-dist-pins.sh after the
build-twice determinism check).

The repo names keep the Phase-1 convention (@openssh_dist, @git_dist, ...).
Because Bazel fetches a repo for the machine it runs on, one repo rule per
product picks the correct URL + sha256 for the current host architecture
(amd64 | arm64). Each repo exposes the checked tarball as
artifact.tar.gz; //image:image re-extracts it into its layer. The tarballs
are layout-compatible with the image: usr/... or etc/... at the top level.
"""

load("//:dist_pins.bzl", "DIST_PINS")

# Product metadata: the artifact basename (matches tools/dist/build-*.sh
# output), the mirror FAMILY tag (openssh-dist, git-dist, ... — the strimserver
# family-tag strategy: one stable release tag per product, re-uploaded with
# --clobber on every pin bump) and the S3 prefix (2.4). Keep in sync with
# tools/dist/versions.sh. The artifact name is the build script's
# product_asset_name output, so "ca-certs" (the pipeline product key) maps to
# the "ca-certificates" artifact name. The repo name is the canonical label
# (underscore form) used by MODULE.bazel use_repo and //image:image.
DIST_PRODUCTS = {
    "openssh": {"name": "openssh", "version": "10.5p1", "prefix": "openssh", "repo": "openssh_dist", "family": "openssh-dist"},
    "git": {"name": "git", "version": "2.53.0", "prefix": "git", "repo": "git_dist", "family": "git-dist"},
    "fish": {"name": "fish", "version": "4.9.3", "prefix": "fish", "repo": "fish_dist", "family": "fish-dist"},
    "sudo": {"name": "sudo", "version": "1.9.17p2", "prefix": "sudo", "repo": "sudo_dist", "family": "sudo-dist"},
    "ca-certs": {"name": "ca-certificates", "version": "20260611-r0", "prefix": "ca-certs", "repo": "ca_certs_dist", "family": "ca-certs-dist"},
    "containerd": {"name": "containerd", "version": "2.3.5", "prefix": "containerd", "repo": "containerd_dist", "family": "containerd-dist"},
    "runc": {"name": "runc", "version": "1.2.9", "prefix": "containerd", "repo": "runc_dist", "family": "runc-dist"},
}

# Artifacts publish to the PRIMARY gitd repo (ChronicCmposer/gitd) under family
# release tags (strimserver pattern); there is no separate gitd-dist repo.
GITHUB_BASE = "https://github.com/ChronicCmposer/gitd/releases/download"
S3_BASE = "https://s3.us-east-2.amazonaws.com/git.cmposer.cc"

# The artifact tarballs have no BUILD file of their own; expose the checksummed
# tarball itself (the image layer genrules extract it deterministically).
_BUILD_FILE = """exports_files(
    ["artifact.tar.gz"],
    visibility = ["//visibility:public"],
)
"""

def _arch_name(repo_ctx):
    arch = repo_ctx.os.arch
    if arch == "x86_64":
        return "amd64"
    if arch == "aarch64":
        return "arm64"
    fail("dist_artifact: unsupported host architecture: " + arch)

def _dist_artifact_impl(repo_ctx):
    arch = _arch_name(repo_ctx)
    sha = repo_ctx.attr.sha256s[arch]
    if sha == "0000000000000000000000000000000000000000000000000000000000000000":
        fail(
            (
                "dist_artifact: {} has no published artifact for {} yet; " +
                "build it with tools/dist/build-*.sh, run make check-*-dist, " +
                "then tools/dist/gen-dist-pins.sh and commit dist_pins.bzl"
            ).format(repo_ctx.name, arch),
        )
    urls = [u.format(arch = arch) for u in repo_ctx.attr.urls]
    repo_ctx.download(
        url = urls,
        sha256 = sha,
        output = "artifact.tar.gz",
    )
    repo_ctx.file("BUILD.bazel", repo_ctx.attr.build_file)

dist_artifact = repository_rule(
    implementation = _dist_artifact_impl,
    attrs = {
        "urls": attr.string_list(mandatory = True),
        "sha256s": attr.string_dict(mandatory = True),
        "build_file": attr.string(mandatory = True),
    },
)

def _dist_impl(_mctx):
    for product, meta in DIST_PRODUCTS.items():
        version = meta["version"]
        asset = "{}-{}.linux-{{arch}}.tar.gz".format(meta["name"], version)
        tag = meta["family"]
        dist_artifact(
            name = meta["repo"],
            urls = [
                "{}/{}/{}".format(GITHUB_BASE, tag, asset),
                "{}/{}/{}".format(S3_BASE, meta["prefix"], asset),
            ],
            sha256s = DIST_PINS[product],
            build_file = _BUILD_FILE,
        )

dist = module_extension(implementation = _dist_impl)