load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "spool",
    srcs = [
        "retry.go",
        "spool.go",
        "uuid.go",
    ],
    importpath = "github.com/ChronicCmposer/gitd/internal/spool",
    visibility = ["//:__subpackages__"],
    deps = ["//internal/event"],
)

go_test(
    name = "spool_test",
    srcs = ["spool_test.go"],
    embed = [":spool"],
    deps = ["//internal/event"],
)
