load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cli",
    srcs = [
        "cli.go",
        "common.go",
        "ddns.go",
        "mirror.go",
        "notify.go",
        "pre_receive.go",
        "serve.go",
        "spool.go",
        "version.go",
    ],
    importpath = "github.com/ChronicCmposer/gitd/internal/cli",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/browse",
        "//internal/config",
        "//internal/disk",
        "//internal/event",
        "//internal/gitenv",
        "//internal/mirror",
        "//internal/objectstore",
        "//internal/objectstore/s3",
        "//internal/repo",
        "//internal/serve",
        "//internal/socket",
        "//internal/spool",
        "//internal/sshcmd",
        "//internal/version",
        "//internal/webhook",
        "//internal/webhook/plugins/http",
        "//internal/webhook/plugins/logger",
        "//internal/webhook/policies/nonfastforward",
    ],
)

go_test(
    name = "cli_test",
    srcs = [
        "cli_test.go",
        "notify_test.go",
    ],
    embed = [":cli"],
    deps = [
        "//internal/config",
        "//internal/disk",
        "//internal/event",
        "//internal/gitenv",
        "//internal/mirror",
        "//internal/objectstore",
        "//internal/socket",
        "//internal/spool",
        "//internal/version",
        "//internal/webhook",
        "//internal/webhook/policies/nonfastforward",
    ],
)
